# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    internal_version_codes = google_play_track_version_codes(track: 'internal')
    max_version_code = internal_version_codes.max
    new_version_code = max_version_code + 1
    gradle(
      task: "clean bundleRelease",
      properties: {
        "android.injected.version.code" => new_version_code
      }
    )
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      package_name: 'com.techthursday'
    )
  end
end
